remote_theme: vfvong/jekyll-theme-tao

# Name of website
title: Language Model Cascades
social-network-links:
  github: google-research/cascades

plugins:
  - jekyll-remote-theme

theme: jekyll-theme-slate